### ISSUE TITLE
Create API documentation

### ISSUE THREAD

**Issue by gigili** [gigili/good-food-tracker-api#37]
There needs to exists a documentation of all API endpoints with description of them and their parameters, also certain routes are only available to certain users so that should be noted in the documentation as well. 

Suggestions for API documentation tools/libraries:
 - [Postman](https://www.postman.com/api-documentation-generator/)
 - [Swagger](https://www.thecodebuzz.com/swagger-openapi-documentation-node-js-and-express-api/)

Here are some articles that might be a good starting point:

[Express API with autogenerated OpenAPI doc through Swagger | Dev.to](https://dev.to/acanimal/express-api-with-autogenerated-openapi-doc-through-swagger-7na)
[How we use Open API v3 specification to auto-generate API documentation, code-snippets and clients | Medium](https://medium.com/pdf-generator-api/how-we-use-open-api-v3-specification-to-auto-generate-api-documentation-code-snippets-and-clients-d127a3cea784)

Any feedback and/or helps is much appreciated on this.

**Comment by aleontief** [comment]
Hi @gigili 
Can I pick this one up?

**Comment by gigili** [comment]
Hey, 
thanks for taking interest. Any help is much welcomed. :)

**Comment by aleontief** [comment]
Okay, could you help me find some initial information about the endpoints?

**Comment by gigili** [comment]
What kind of information do you need ?

All the routes are stored in the routes folder split into files depending on the grouping. 

So for example all the endpoints related to user profile are in an routes/profile.ts file and than separated by a type od request they accept (GET,PUT,POST, etc ). 

GET - just returns data 
POST - creates a new record 
PUT/PATCH - updates a record
DELETE - removes the record

**Comment by aleontief** [comment]
All right, the routes folder. Thanks.

**Comment by gigili** [comment]
No problem, if you need any other help, feel free to ask :)

**Comment by kabartolo** [comment]
Hi @gigili, I'm interested in contributing.

@aleontief are you still working on this? Happy to join forces if there's anything I can do.

Thanks :)

**Comment by aleontief** [comment]
Hi Kate,

Will be glad to hand the reins over to you, as I still can't find time for
this project.

вт, 10 нояб. 2020 г., 20:27 Kate Bartolo <notifications@github.com>:

**Comment by gigili** [comment]
Hey @kabartolo  

If @aleontief  are cool with the please do.

Any help is appreciated and welcomed  :)

**Comment by kabartolo** [comment]
Awesome! I'll get started

**Comment by kabartolo** [comment]
Hi Igor,
Do you have a preference between Postman and Swagger? 

I think the Swagger method in the first article you posted seems the most straightforward. It's the method involving `swagger-jsdoc` and `swagger-ui-express`. Documentation can be added to each file directly using JSDoc, and this should then be considered the source of truth for that route's documentation. I think this makes it easy to contribute changes to the docs later. 

I think there's also a way to autogenerate code samples with [`openapi-snippet`](https://github.com/ErikWittern/openapi-snippet).

Then in terms of making the docs available to users, a route such as `/api-docs` can be added to the API itself (using `swagger-ui-express`). Is this what you were thinking?

Thanks :)

**Comment by gigili** [comment]
I don't have any real preference between the Postman and Swagger. 

But yeah from your suggestions and everything I was able to find about it online, swagger looks like a better choice for this. So you can go with Swagger. Also like the idea about `api-docs` endpoint or just the `docs` endpoint for it.

**Comment by abwriting** [comment]
Hello Igor, Kate,
Hope you are doing great.
I am a technical writer interested in jumping into API documentation, have completed courses pertaining to it.
Would like to get some hands on experience via open source project and found yours in GitHub.
Please let me know if I can contribute to your project's documentation.
If yes, please let me know if the project uses REST APIs. Many thanks.

**Comment by kabartolo** [comment]
Hi Abrar,
Nice to meet another technical writer!

I've been setting up Swagger UI for this project, and I've written the documentation for one route (plus some of the root information for the project, like the title). If it's okay with Igor, you and I could split the rest of the routes for documentation.

I have some free time today, so I should have a pull request by tomorrow for Igor to review. I'll include the docs I've already written.

The project is a REST API. The docs would be written in [JSDoc](https://jsdoc.app/) (YAML syntax) to follow the [OpenAPI Specification](https://swagger.io/specification/).

**Comment by gigili** [comment]
If that works for both of you, I'm totally fine with that. Any and all help is appreciated :)

**Comment by kabartolo** [comment]
Happy to help!

Igor, I forgot to mention, there is currently a type error when running the app: `TypeError: utilities.authenticateToken is not a function`. It might have been introduced in b314d39c80f068e87d4b25c49d503ef1bb07557f. 

It is fixed by changing `authenticateToken` to `authenticate_token` in all the route files. Would you like me to create a separate issue?  Or I can include this fix in my pull request if that helps. Thanks :)

**Comment by gigili** [comment]
You can include it with your pr

**Comment by abwriting** [comment]
Thank you Kate, looking forward to seeing the Swagger UI and the documentation for the route you created to familiarize with the format.

In the meanwhile, I will explore the project as a whole. Will follow your lead.

**Comment by kabartolo** [comment]
Hi Igor and Abrar,
I ended up writing the docs for all the City routes to make the review and discussion process more efficient (see the recent pull request). This way we can look at all the types of routes at the same time. Abrar, I hope you'll comment and let me know your thoughts as well. :)

I'll be away for a few days, but let me know if you have any questions.

**Comment by gigili** [comment]
Hey 

Thank you for the pr. I will review it as soon as I can, and get back to you with any additional information or feedback. From a quick glance at it looks good.

**Comment by abwriting** [comment]
Hi Kate, thank you for pointing towards the documentation, I am still trying to break the code as my JSON and PYTHON skills are questionable:-)

**Comment by kabartolo** [comment]
Hey Abrar! You probably don't need to understand too much of the code (unless you want to of course). When the `routes/city.ts` docs are finished, I'm hoping we can just copy and paste the JSDoc comments to the other route files. We would just need to change the specific messages and descriptions. I'll walk you through what to do when you're ready to start writing. :)

I should have a few more commits up today! Hoping to get `city.ts` finished soon.

**Comment by dibyaranjangithub** [comment]
Hi @kabartolo Are you still working on this project? I can see you have completed  `route/city.ts is` , however, I am not sure if other routes are done. I am a technical writer, wants to practice on open source API documentation, and would like to work with you (with your guidance of course:)) on this. I was going through the chat, and with your PR. Can we work together if you are still working on this and are Ok with my request?

**Comment by kabartolo** [comment]
Hi @dibyaranjangithub , it would be great to have your help if @gigili is okay with it!

I haven't had the time to add more documentation. But I'll be back from holiday next week, and I can start working with you then.

Please go ahead and start writing docs for any of the other routes if you want to!  The docs for the other routes will be very similar to the docs for `city.ts`. You can also refer to the [Swagger docs](https://swagger.io/docs/specification/about/). Let me know if you have any questions. :)

**Comment by gigili** [comment]
Yeah I'm perfectly fine with anyone contributing to the documentation. Thank you all for all your help :+1:

**Comment by shivangim-API** [comment]
@gigili, do you still need help with the API documentation?

**Comment by gigili** [comment]
Hey @shivangim-API,

thank you for reaching out. If @kabartolo isn't working on this, or if she can use help with it, I'm perfectly fine with you contributing. The documentation is still needed for the project.

**Comment by shivangim-API** [comment]
@kabartolo let me know if you need any help with the project.

**Comment by kabartolo** [comment]
Hi @shivangim-API, it would be great to have some help. I haven't been working on this project since we've had so much interest from other writers. I want to give others a chance to work on it.

Please go ahead with writing some documentation, and if you need any help, don't hesitate to ask. If you aren't sure where to start, I can guide you in the right direction :)

**Comment by shivangim-API** [comment]
@kabartolo thanks. Some help towards the right direction would be great.

**Comment by kabartolo** [comment]
@shivangim-API No problem. The files that need docs are in the `routes` folder. The `routes/city.ts` file has documentation already, so you can start by reviewing that file. You'll notice some code comments that start like this:

```
/**
 * @swagger
```

These are JSDoc comments that Swagger uses to build a docs page. I would suggest going through these comments to see how they work and how they relate to the code. To understand the Swagger syntax, check out the [Swagger documentation](https://swagger.io/docs/specification/basic-structure/). 

To see the Swagger UI page that displays the documentation, first clone this repository, then run `npm install` and `npm run dev`. Then navigate to `localhost:3000/docs` in your browser. You'll see all the docs from `routes/city.ts`. When you add more docs in other route files, they'll show up here as well. Let me know if you need further help with this.

In the first comment in this thread above, there are two tutorials that explain how all of this works. I also wrote a tutorial that breaks down the process: [How to Document an Express API with Swagger UI and JSDoc](https://dev.to/kabartolo/how-to-document-an-express-api-with-swagger-ui-and-jsdoc-50do)

Hope that helps!

**Comment by beckkim24** [comment]
Hi Kate, 
I would like to help out on this project as well if that's okay. I've cloned the repository and ran `npm install` and `npm run dev`, but when I navigate to `localhost:3000/docs` in my browser, I see an error message that says "this site can't be reached". Do you know what I could do on my end to fix this? 

Thank you and pls let me know if it's okay if I can join. :)

**Comment by kabartolo** [comment]
Hey @beckkim24, you're welcome to join! 

Sorry, that should have said `localhost:3001/docs`. Try that and let me know if it works :)

Please let me know if you have any more issues!

**Comment by tanaya0214** [comment]
Hi @kabartolo , I'm a new technical writer looking to get involved with API documentation and this seemed like a great project to help you with if you're still working on it and are willing to take on a newer writer. I've dabbled in some Swagger, Postman, and Spotlight so far, but I feel I learn pretty quickly. Please let me know!

**Comment by kabartolo** [comment]
Hi @tanaya0214 , I'm sorry I missed your comment. Please go ahead and work on this if you are still interested. See my [comment ](https://github.com/gigili/good-food-tracker-api/issues/37#issuecomment-769484280) above for guidance, and feel free to ask me any questions.
